vault_version: "1.18.3"
vault_user: vault
vault_group: vault
vault_config_dir: /etc/vault.d
vault_data_dir: /opt/vault/data
vault_log_dir: /var/log/vault
vault_address: "0.0.0.0"
vault_port: 8200
vault_cluster_port: 8201
vault_ui_enabled: true
vault_log_level: info
vault_disable_mlock: true
