---
- name: Install HAProxy
  ansible.builtin.dnf:
    name: haproxy
    state: present

- name: Deploy HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
    validate: haproxy -c -f %s
  notify: Reload haproxy

- name: Allow HAProxy to bind to Vault port with SELinux
  ansible.builtin.command:
    cmd: setsebool -P haproxy_connect_any on
  changed_when: false

- name: Open HAProxy frontend port in firewalld
  ansible.posix.firewalld:
    port: "{{ haproxy_frontend_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled

- name: Open HAProxy stats port in firewalld
  ansible.posix.firewalld:
    port: "{{ haproxy_stats_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  when: haproxy_stats_enabled

- name: Enable and start HAProxy
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
    state: started
