---
- name: Install and configure HashiCorp Vault
  hosts: vault_servers
  become: true

  roles:
    - vault

- name: Install and configure HAProxy for Vault
  hosts: haproxy_servers
  become: true

  roles:
    - haproxy
